Module2 task1
htmlacademy-react/1599147-six-cities-13 pull request #2
Opened 2023-07-08 20:19 UTC by dimpulsha

2023-07-10 15:15 UTC, Pavel-Liteiniy requested changes

2023-07-10 15:15 UTC, Pavel-Liteiniy commented on src/components/header-nav/header-nav.tsx
> +        <User />
```suggestion
        <li><User /></li>
```

2023-07-10 15:15 UTC, Pavel-Liteiniy commented on src/config/cities-list.ts
src/constants.ts

2023-07-10 15:15 UTC, Pavel-Liteiniy commented on src/index.tsx
> +    <App />
> В файле index.tsx опишите данные, которые нужны в компоненте главной страницы приложения. Передайте их в компонент App.
> 
> В App получите эти данные из props и передайте их в компонент главной страницы приложения.

2023-07-10 15:15 UTC, Pavel-Liteiniy commented on src/pages/main/main.tsx
> +  const fakeArray = new Array(props.placesCount);
```suggestion
  const fakeArray = Array.from({ length: props.placesCount}, () => {})
```

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/from

2023-07-12 10:18 UTC, dimpulsha commented on src/index.tsx
> +    <App />
исправлено

2023-07-12 10:19 UTC, dimpulsha commented on src/config/cities-list.ts
сделал похожим образом, но чуть по-другому

2023-07-12 10:21 UTC, dimpulsha commented on src/components/header-nav/header-nav.tsx
> +        <User />
Пока исправил как требуется, но возникает вопрос в динамическом формировании  элементов списка в зависимости от авторизации. пока отложил этот вопрос.

2023-07-12 10:48 UTC, merged